Repository udaan-com/snorql, pull requests merged in 2022-02, with the labels that each got.

#66 Added CI/CD for maven & github release
  .github/workflows/build.yaml
  .github/workflows/release-with-major-update-for-next.yaml
  .github/workflows/release-with-minor-update-for-next.yaml
  .github/workflows/release-with-patch-update-for-next.yaml
  pom.xml
  release-notes/README.md
  release-notes/v0.4.20.md
  release-notes/v0.4.21.md
  snorql-extensions/pom.xml
  snorql-framework/pom.xml
Labels: size/L

#65 Adding Persistence Data Support in Snorql
  default-detekt-config.yml
  pom.xml
  pull_request_template.md
  snorql-extensions/pom.xml
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/accesscontrol/metrics/UserRoleMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/performance/metrics/ActiveDDLMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/performance/metrics/ActiveQueriesMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/performance/metrics/BlockedQueriesMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/performance/metrics/IndexStatsMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/performance/metrics/LongRunningQueriesMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/DbGrowthMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/DbIndexMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/DbMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/DbTableMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/PVSMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/TableMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/TableSchemaMetric.kt
  snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/storage/metrics/TableUnusedIndexMetric.kt
  snorql-extensions/src/main/resources/sql-monitoring-conf.json
  snorql-framework/pom.xml
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/Exceptions.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/IMtericId.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/job/DataPersistenceJob.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/job/JobManager.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/metric/Connection.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/metric/IMetric.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/metric/Logging.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/metric/QueryExecutor.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/models/Configuration.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/models/JobDTOs.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/models/MetricPeriod.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/models/MetricsDTOs.kt
  snorql-framework/src/main/kotlin/com/udaan/snorql/framework/models/SnorqlConstants.kt
Labels: enhancement, size/XL

#68 snorql maven release to 0.5.0-SNAPSHOT
  pom.xml
  pull_request_template.md
  release-notes/v0.5.0.md
  snorql-extensions/pom.xml
  snorql-framework/pom.xml
Labels: documentation, size/S

#71 Edit README: fix typo + cleanup
  README.md
Labels: size/XS

#72 README: Fillup missing sections + fix typos
  README.md
  doc/docs/index.md
  doc/docs/sections/acknowledgements.md
  doc/docs/sections/contacts.md
  doc/docs/sections/roadmap.md
  doc/docs/sections/title.md
  release-notes/v0.5.0.md
Labels: size/M
